image: ubuntu:22.04

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - apt-get update || true
  - apt-get -y install curl make g++ pandoc
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source $HOME/.local/bin/env

deploy:
  stage: deploy
  tags:
    - flores.docs@docker
  only:
    - main
  script:
    - UV_CACHE_DIR=".uv-cache" CXX="g++" make docs
    - mkdir -p $DOCS
    - rm -rf $DOCS/*
    - cp -R docs/build/* $DOCS/
